### ISSUE TITLE
Found unconventional releases

### ISSUE THREAD

**Issue by hk2cmpny** [immera/payment-frontend#5]
**Problem**

1. GitHub repo release version doesn't match with npm package release version.
2. Even thought there is automated flow define to make them auto release we are not using them.

**Proposed solution**

Enable automated release and both the problem will be resolved. more over, developer can be independent to release new version and don't wait for anyone to release for them.

_Note: New possible issue is release version convention. so I would prefer to prepare a guideline for that._

**Steps**

npm account owner need to go to npm tokens (https://npmjs.com/settings/[[username]]>/tokens) page (if the package owner is @promatik  then possible page link is https://npmjs.com/settings/promatik/tokens)

generate new token for auto release.

then go to (repo secret manage page)[https://github.com/immera/mccm-frontend/settings/secrets/actions] and add new secret with name `AUTOMATED_PUBLISH` and put the secret value there.

once this is done everything when we release new tag in github reppo it will automatically release the new version in the npm. (we need to make sure when we release new version at the same time also need to maintain the same version in the package.json. because npm will pick up version from package.json)

**Comment by promatik** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1838187/174982574-5f1d0816-f325-4596-971c-cfa6579dd831.png">

The key was added.
